### ISSUE TITLE
 Attach SharePoint Document library files to a Dataverse email record

### ISSUE THREAD

**Issue by yodo94** [GorgonUK/Modern-Dropzone-PCF#18]
Hi,
This is not an issue but a suggestion.
Would it be possible to attach SharePoint Document library files to a Dataverse email record (Model Driven App) ?
Thank you.
Youcef

**Comment by GorgonUK** [comment]
Hi Youcef,

It certainly is, but it requires investigation first. I'll let you know when I have more information.

**Comment by yodo94** [comment]
Hi Georges
Thank you.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : George Kontus ***@***.***>
Envoyé : Monday, August 19, 2024 8:36:47 PM
À : GorgonUK/Modern-Dropzone-PCF ***@***.***>
Cc : yodo94 ***@***.***>; Author ***@***.***>
Objet : Re: [GorgonUK/Modern-Dropzone-PCF] Attach SharePoint Document library files to a Dataverse email record (Issue #18)


Hi Youcef,

It certainly is, but it requires investigation first. I'll let you know when I have more information.

**Comment by GorgonUK** [comment]
> Hi, This is not an issue but a suggestion. Would it be possible to attach SharePoint Document library files to a Dataverse email record (Model Driven App) ? Thank you. Youcef

Adding a SharePoint document to activity attachments is not possible due to SharePoint's "cross origin" rules. SharePoint doesn't allow it's files to be accessed over REST from an external website i.e Dynamics
You would likely face an error like this:
![image](https://github.com/user-attachments/assets/3e86430d-3e05-4023-aba1-1daae0b54a51)

In conclusion, the requirement is only possible with a proxy i.e APIM or App registration.

**Comment by yodo94** [comment]
Hi Georges,
I did not understand the conclusion.....
The ideal would be to have been to be able to have a preview of a selected Word template and then have the options to Save localy, Save on SharePoint and Email the generated Pdf file as an attachment like it is done in Microsoft Sales App.
Best regards.
Youcef
